version: '3.8'

services:
  # AI Observer as sidecar
  observer:
    build: .
    container_name: axom-observer
    ports:
      - "8888:8888"   # HTTP proxy
      - "8443:8443"   # HTTPS proxy
    environment:
      - CUSTOMER_ID=${CUSTOMER_ID:-test-customer}
      - AGENT_ID=${AGENT_ID:-test-agent}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8080/api/v1/signals}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./certs:/app/certs:ro  # Mount certificates if needed
      - observer-logs:/app/logs
    networks:
      - observer-network
    restart: unless-stopped

  # Demo AI app for testing
  demo-ai-app:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: demo-ai-app
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
    networks:
      - observer-network
    restart: unless-stopped
    depends_on:
      - observer

  # Backend service for receiving signals
  backend:
    image: nginx:alpine
    container_name: signal-backend
    ports:
      - "8080:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/html:/usr/share/nginx/html:ro
    networks:
      - observer-network
    restart: unless-stopped

volumes:
  observer-logs:

networks:
  observer-network:
    driver: bridge